Batch scheduling implementation and tests
cccs-mog/CAPEv2 pull request #1
Opened 2023-10-30 14:49 UTC by cccs-mog

2023-10-30 17:10 UTC, cccs-kevin requested changes

2023-10-30 17:10 UTC, cccs-kevin commented on conf/cuckoo.conf.default
> -# A configurable wait time between updating the limit value of the scaling bounded semaphore
we still want this comment

2023-10-30 17:10 UTC, cccs-kevin commented on conf/cuckoo.conf.default
> +batch_scheduling = on
add comment explaining what this is, also default should be `off`

2023-10-30 17:10 UTC, cccs-kevin commented on conf/cuckoo.conf.default
> +max_batch_count = 5
add comment explaining what this is

TODO: do we need this feature set to such a low number?

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    @classlock
the only difference between this method and `is_relevant_machine_available()` is the setting of the task status. We can just add a keyword argument to `is_relevant_machine_available()` instead such as `set_status` that defaults to `True`, and then when we need that method, we can just set that keyword argument to `False`. That will save us some code

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        # if machine_id:
This commented out code block can be deleted

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    def db_relevant_machines_to_tasks(self, tasks) -> []:
Method should not start with `db_` since it is in the `database.py` file

Rename method to describe what it is doing. `relevant_machines_to_tasks` needs an action word

The type hinting here should be `(self, tasks: list) -> list:`

Add a docstring comment explaining the expected inputs and outputs and what the method will do. Look at other methods in this file for examples.

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    # Preventive checks.
This is the same logic as `lock_machine`. I think both of these methods should reuse a smaller method that performs the preventative checks with label/machine, platform and tags. It should be performed prior to the session usage too in both of the methods.

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    machines = session.query(Machine).options(joinedload(Machine.tags)).filter_by(locked=False)
this can be replaced by the method `get_available_machines()`

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    if task.machine:
I think this machine filtering which is duplicated here, in `count_machines_available`, `list_machines` and `lock_machine` should be a shared method.That way the logic is consistent and expected for each of these methods.

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                        # machines = machines.filter(Machine.tags.all(Tag.name.in_(tags)))
remove comment

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    #machine = machines.filter(Machine.label.not_in(assigned_machines)).first()
remove comment

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    for assigned in assigned_machines:
Add a comment above this for loop explaining why this filter is applied

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    return []
should we bail on all batch scheduling if a single round of the loop fails? I'm not sure what the right answer is, we could use a `continue` statement rather than returning, but also, I'm not sure what is preferred...

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +            if selected_vm is not None:
I think this `selected_vm` logic should move above to inside the `if machine:` condition. The variable seems redundant

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +    In this version of semaphore there is a upper limit where it's limit value
```suggestion
    In this version of semaphore there is an upper limit where its limit value
```

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            raise ValueError("can't specify timeout for non-blocking acquire")
```suggestion
            raise ValueError("Cannot specify timeout for non-blocking acquire()")
```

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                #log.info("Lock release in vain!!!")
remove comment

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            #log.info("Lock limit changed to %s from %s with current value at %s",value,self._limit_value,self._value)
remove comment

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            log.info("Active analysis: %s" % active_analysis_count)
remove log, lock logs would be too noisy, even for debug mode

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            log.debug("Lock got fully starved, reinitializing it")
remove log, lock logs would be too noisy, even for debug mode

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            log.debug("Lock partially starved %s/%s with %s: active at %s and available at %s" % (self._value,self._limit_value,current_drift,active_analysis_count,available_count))
remove log, lock logs would be too noisy, even for debug mode

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                # new guest when the task is being analyzed with another
not necessary and distracts from PR purpose

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +
not necessary and distracts from PR purpose

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> -                # Release the analysis machine. But only if the machine has not turned dead yet.
not necessary and distracts from PR purpose

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> -                # First we have to remove the existing symbolic link, then we have to create the new one.
not necessary and distracts from PR purpose

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +		# You set this value if you are using a machinery that is NOT auto-scaling
incorrect indentation

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> + 		# If the user wants to use the scaling bounded semaphore, check what machinery is specified, and then
incorrect indentation

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> -        max_vmstartup_count = self.cfg.cuckoo.max_vmstartup_count
why was this moved?

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        	# The BoundedSemaphore is used to prevent CPU starvation when starting up multiple VMs
incorrect indentation for comments in this `if` statement

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +			# Note that this variable only exists under these conditions
incorrect indentation

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        if task_scheduled > 0:
if the purpose of `task_scheduled` is for debugging performance only, then I think it should be removed from this PR

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            max_batch_scheduling_count = self.cfg.cuckoo.max_batch_count if self.cfg.cuckoo.max_batch_count else 5
perform checks against negative values

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            # when all machines are fully running, rather that about to start
```suggestion
            # when all machines are fully running, rather than "about to start"
```

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            # or still busy starting. This way we won't have race conditions
```suggestion
            # or "still busy starting". This way we won't have race conditions
```

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                if scaling_semaphore_timer + int(self.cfg.cuckoo.scaling_semaphore_update_timer) <time.time():
```suggestion
                if scaling_semaphore_timer + int(self.cfg.cuckoo.scaling_semaphore_update_timer) < time.time():
```

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +    def check_for_starvation(self,available_count):
```suggestion
    def check_for_starvation(self, available_count: int):
```

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        if abs(self._value - available_count) > 0:
why is `abs` used? Can the `available_count` be greater than `self._value` and we need to check the net diff here?

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> -            # ToDo verify that it works with static and file/url
has this been done in this PR?

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                        tasks = []
can this variable name be more specific? such as `tasks_with_relevant_machine_available`

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                        batching_number = max_batch_scheduling_count if machine_lock._value > max_batch_scheduling_count else machine_lock._value
A comment here explaining why these values are used and what `batching_number` represents would be nice

2023-10-30 17:10 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                        relevant_tasks = self.db.db_relevant_machines_to_tasks(tasks)
Need a different name for the variable to represent what this method is returning

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +        inspector = inspect(self.d.engine)
is this code required or is this relative to our setup?

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +            #Assign 10 tasks to 10 specific machines availables
```suggestion
            # Assign 10 tasks with the same tag to 10 available machines with that tag
```

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +             [("windows","x64","tag1",10),("windows","x86","tag2",5),("linux","x64","tag3",2)],
no need to complicate this first test case
```suggestion
             [("windows","x64","tag1",10)],
```

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +        "task_instructions,machine_instructions,expected_results,function",
I think we need a comment here explaining what each of these variable names represents and their format

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +            #Assign 10 tasks to 10 specific machines availables
```suggestion
            # Assign 10 tasks (8 with one tag, 2 with another) to 8 available machines with that tag and 2 available machines with the other tag
```

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +             [("windows","x64","tag1,",10),("windows","x86","tag2,",2),("linux","x64","tag3,",2)],
Let's keep things simple as we ramp up the test cases
```suggestion
             [("windows","x64","tag1,",8),("windows","x86","tag2,",2)],
```

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +            #Assign tasks to their specific tags based on the number of machines for each of them
```suggestion
            # Assign 43 tasks total containing a variety of tags to 40/80 available machines with the first tag, 2/2 available machines with the second tag and 1/2 available machines with the third tag
```

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +                task = self.d.add_path(file_path=sample_name,tags=task_instruction[0])
rename variable to `task_id`

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +        print("Number of tasks: %d" % len(tasks))
remove prints from unit test

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +        print("Total number of tasks that should be assigned: %d" % total_task_to_be_assigned)
remove prints from unit test

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +    def test_db_batch_submission(self,task_instructions,machine_instructions,expected_results,function):
the method is always `db_relevant_machines_to_tasks`, so this logic should be removed to have a generic `function` parameter, and the method should be renamed `test_<method_name_to_be_tested>`

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +        while len(tasks) > 0:
I don't think this while loop logic should for the test. The theory behind the test is that we should just pass inputs to the method and validate the output is what is expected

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +        if total_task_assigned != total_task_to_be_assigned:
this should be an `assert` instead

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +                    errors.append("Unexpected number of tasks assigned for tags")
this should be an `assert`

2023-10-30 17:10 UTC, cccs-kevin commented on tests/test_database.py
> +        if machine["tags"] != None:
this unit test needs to be reworked, there is too much logic and too many references to other methods/classes.

The general flow of this test should be as follows:
1. Create Task from task details
2. Create Machine from machine details
3. Call the method you are trying to test (self.d.lock_machine)
4. Validate output and expected system behaviour

2023-10-30 18:29 UTC, cccs-mog commented on lib/cuckoo/core/database.py
> +                    machines = session.query(Machine).options(joinedload(Machine.tags)).filter_by(locked=False)
Should I be creating multiples sessions in the DB for this ? I understand the idea of not recreating parts so it's easier to modify/make thing cleaner at the code level but it should not take priority over clean execution. What do you think ?

2023-10-30 18:37 UTC, cccs-mog commented on lib/cuckoo/core/database.py
> +                    return []
We can't know exactly where the try statement failed in the reading/filtering, so to avoid any inconsistent result we bail. This is the cost of making sure that there is no double spending.

2023-10-30 18:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    machines = session.query(Machine).options(joinedload(Machine.tags)).filter_by(locked=False)
There are a few methods in `database.py` that favour clean code and use sessions within sessions, so I think that is the route that we should be taking (for example, `self.set_status()` usage within other methods that have sessions)

2023-10-30 18:40 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    return []
Roger that! Resolving...

2023-10-30 18:51 UTC, cccs-mog commented on lib/cuckoo/core/scheduler.py
> +        if abs(self._value - available_count) > 0:
Exactly, this is a unlikely but possible event which would falsely make the condition false. (available count is from the DB) and self._value is from the lock. I am looking for drift between the two values in either direction not just one.

2023-10-30 18:53 UTC, cccs-mog commented on lib/cuckoo/core/scheduler.py
> -            # ToDo verify that it works with static and file/url
No this is pollution from my previous PR which was merged with godspeed by doomsraven... This was fixed by someone else before in prod and the comment was removed but reappeared in my old PR.

2023-10-30 18:54 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        if abs(self._value - available_count) > 0:
okay great

2023-10-30 19:02 UTC, cccs-mog commented on tests/test_database.py
> +        inspector = inspect(self.d.engine)
I don't think it's related to our setup, it is also much cleaner. I don't think there could be unintended consequences from it and it is not related to our setup as my clean test run required it for the new tests to work (ubuntu machine with clean fork)

2023-10-30 19:35 UTC, cccs-kevin commented on tests/test_database.py
> +        inspector = inspect(self.d.engine)
Okay sounds good, please add a comment here explaining why this has to be done before each test :)

2023-10-30 19:50 UTC, cccs-mog commented on lib/cuckoo/core/database.py
> +                    if task.machine:
The expected code to be wrapped together is : 
`                  if task.machine:
                        machines = machines.filter_by(label=task.machine)
                    else:
                        machines = machines.filter_by(reserved=False)
                    if task.platform:
                        machines = machines.filter_by(platform=task.platform)
                    machines = self.filter_machines_by_arch(machines, task_archs)
                    if task_tags:
                        for tag in task_tags:
                            machines = machines.filter(Machine.tags.any(name=tag))
                    if os_version:
                        machines = machines.filter(Machine.tags.any(Tag.name.in_(os_version)))`

2023-10-30 19:55 UTC, cccs-mog commented on lib/cuckoo/core/database.py
> +                    machines = session.query(Machine).options(joinedload(Machine.tags)).filter_by(locked=False)
Thing to validate : Does a query object be created before using filters or a list of machines object can be queried on ?

2023-10-30 20:24 UTC, cccs-mog commented on tests/test_database.py
> +        if machine["tags"] != None:
Need to be discussed as multiple fixes possibles.

2023-10-31 16:15 UTC, cccs-mog commented on tests/test_database.py
> +        if machine["tags"] != None:
The main reason this test have this much logic is the idea of testing every aspect of the function (testing all parameters to see if they work. The step taken are :
1)Creating the machine to be tested 
2)Locking the machine manually if specified
3)Creating the task to be tested
4)Getting the extra information needed about the task
5)Testing the function
6)Validating the output and cleanup
As far as I am concerned I think the only step that could be omitted is the manual locking even thought it test a possible branch of the function ?

2023-10-31 18:38 UTC, cccs-kevin requested changes
Getting closer!!!

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    def validate_tasks_parameters(self,label,platform,tags) -> bool:
This is a nitpick, but I think it is important to note that this method is only used for the parameters of a single task
```suggestion
    def validate_task_parameters(self,label,platform,tags) -> bool:
```

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        @param task to validate
add docstring for `set_status`

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        @param label of the machine asked for by the task
```suggestion
        @param label: label of the machine asked for by the task
```

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        @platform platform of the machine asked for by the task
```suggestion
        @param platform: platform of the machine asked for by the task
```

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        @tags tags of task
```suggestion
        @param tags: tags of task 
```

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        @param task to validate
```suggestion
        @param task: task to validate
```

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        @param List of tasks to filter
```suggestion
        @param tasks: List of tasks to filter
```

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        """ Add filters to the given query based on the task"""
need docstring for params and return value

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    def filter_machines_to_task(machines,label=None,platform=None,tags=None,archs=None,os_version=[],include_reserved=False):
```suggestion
    def filter_machines_to_task(machines: list, label=None, platform=None, tags=None, archs=None, os_version=[], include_reserved=False):
```

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            log.debug("Lock partially starved %s/%s with %s: active at %s and available at %s" % (self._value,self._limit_value,current_drift,active_analysis_count,available_count))
log still exists

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> + 		# If the user wants to use the scaling bounded semaphore, check what machinery is specified, and then
not resolved

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +            log.debug("Lock got fully starved, reinitializing it")
not resolved

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +
remove whitespace change, distracts from PR feature

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        	# The BoundedSemaphore is used to prevent CPU starvation when starting up multiple VMs
not resolved

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        	# The ScalingBoundedSemaphore is used to keep feeding available machines from the pending tasks queue
incorrect indentation

2023-10-31 18:38 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +			# Note that this variable only exists under these conditions
not resolved

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +        for result in expected_results.values():
#oneliner
```suggestion
        total_task_to_be_assigned = sum(expected_results.values())
```

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +            for i in range(machine_instruction[3]):
since you're using tuples, I think you should split the tuples into variables rather than using `range` values because it will be easier to read that way. For example:
```
machine_instruction = ("windows","x64","tag1",80)
platform, arch, tag, num_of_machines = machine_instruction
```

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +            for i in range(task_instruction[1]):
see tuple suggestion above to apply here

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +            for i in range(len(results)):
see tuple suggestion above to apply here

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +            for i in range(len(results)):
see tuple suggestion above to apply here

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +        if expected_result[1]:
It is not clear to me what this value represents when reading the tests, please assign tuple values to variables

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +        assert len(self.d.get_available_machines()) == expected_result[0]
same as above

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +
so the only `assert` for this method so far is the length of available machines? 

We should be able to test the `return` value from `lock_machine` as well as the `locked` value of the returned machine

2023-10-31 18:38 UTC, cccs-kevin commented on tests/test_database.py
> +        if machine["tags"] != None:
Hmmm I think what I'm struggling with is the fact that `add_machine` doesn't return a machine ID/machine object AND doesn't provide the ability to pass `locked=True` to lock a machine... So we have to use custom code in a unit test just to facilitate this capability... Ah well, that is a problem for another day I guess.

If these methods change: `_task_arch_tags_helper()` and `_package_vm_requires_check()`, then our unit test that is supposed to only test a single method will now have different data, so I think we should hard-code these values into the unit test `parametrize` parameters.

Otherwise, you've convinced me that this is the way!

2023-10-31 19:46 UTC, cccs-mog commented on tests/test_database.py
> +            for i in range(machine_instruction[3]):
This change won't eliminate the range values, only refering to machine instruction by name instead of index in the list (which is probably more readable so implementing it)

2023-10-31 20:32 UTC, cccs-mog commented on tests/test_database.py
> +
I am able to test the locked status of the outputed machine however the is keyword doesn't seem to be working and __eq__ implementation would mean changing the class in the database file only for test which seem excessive. Any suggestion ?

2023-11-01 12:18 UTC, cccs-kevin commented on tests/test_database.py
> +
the `is` keyword should work if checking boolean equality, it should be `assert locked_machine.locked is True`. If this doesn't work, let's do a call today

2023-11-01 13:38 UTC, cccs-mog commented on tests/test_database.py
> +
Yes checking the locked status of the returned machine work, what is not working is validating the output value of the function (the machine itself) is the one that was created (it's the only machine on the system so it's 100% sure to pass) the is keyword is not working on this case.

2023-11-01 13:41 UTC, cccs-kevin commented on tests/test_database.py
> +
Ah okay, `==` should work for class object equality, but if it doesn't, then you can use `assert expected_machine.__dict__ == returned_locked_machine.__dict__`

2023-11-01 14:46 UTC, cccs-mog commented on tests/test_database.py
> +
Tried what you suggested and it would seem that the initial query is not the same and one of the object is joined with the machine tags and not the other. It should be not changed in the database file ? (i.e lock_machine() output machine object is not joined with the tags as most other function to grab machines are. I will try to make the assert work without modifying the database file only for the test.

2023-11-01 14:51 UTC, cccs-kevin commented on tests/test_database.py
> +
if you are comparing dictionaries with `._dict__`, just `.pop()` the values that you don't want prior to doing the `assert`

2023-11-01 17:12 UTC, cccs-mog commented
Correcting errors that have been made during Git manupulation. Next commit is going to be the correct one

2023-11-02 15:39 UTC, cccs-kevin requested changes

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    def validate_task_parameters(self,label,platform,tags) -> bool:
```suggestion
    def validate_task_parameters(self, label: str, platform: str, tags: list) -> bool:
```

2023-11-02 15:39 UTC, cccs-kevin commented on conf/cuckoo.conf.default
> +#The number of tasks that should be assigned to machine at once,optimal maximum highly dependant on deployment
```suggestion
# The number of tasks that should be assigned to machine at once, optimal maximum highly dependant on deployment
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    def is_relevant_machine_available(self, task: Task,set_status=True) -> bool:
```suggestion
    def is_relevant_machine_available(self, task: Task, set_status: bool = True) -> bool:
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        @param task : task to validate
```suggestion
        @param task: task to validate
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    machines = self.filter_machines_to_tasks(machines=machines,label=task.machine,platform=task.platform,tags=task_tags,archs=task_archs,os_version=os_version)
```suggestion
                    machines = self.filter_machines_to_task(
                          machines=machines,
                          label=task.machine,
                          platform=task.platform,
                          tags=task_tags,
                          archs=task_archs,
                          os_version=os_version
                    )
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    #This loop is there in order to prevent double spending of machines by filtering out already mapped machines
```suggestion
                    # This loop is there in order to prevent double spending of machines by filtering out already mapped machines
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                     # Get the first free machine.
```suggestion
                    # Get the first free machine.
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    def filter_machines_to_tasks(self,machines: list,label=None,platform=None,tags=None,archs=None,os_version=[],include_reserved=False) -> list:
```suggestion
    def filter_machines_to_tasks(
        self, 
        machines: list, 
        label=None, 
        platform=None, 
        tags=None, 
        archs=None, 
        os_version=[], 
        include_reserved=False
    ) -> list:
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        """ Add filters to the given query based on the task
```suggestion
        """ Add filters to the given list of machines based on the task
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                machines = self.filter_machines_to_tasks(machines=machines,label=label,platform=platform,tags=tags,archs=arch,os_version=os_version,include_reserved=include_reserved)
```suggestion
                machines = self.filter_machines_to_tasks(
                    machines=machines,
                    label=label,
                    platform=platform,
                    tags=tags,
                    archs=arch,
                    os_version=os_version,
                    include_reserved=include_reserved
                )
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +        if not self.validate_task_parameters(label=label,platform=platform,tags=tags):
```suggestion
        if not self.validate_task_parameters(label=label, platform=platform, tags=tags):
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                machines = self.filter_machines_to_tasks(machines=machines,label=label,platform=platform,tags=tags,archs=arch,os_version=os_version)
```suggestion
                machines = self.filter_machines_to_tasks(
                    machines=machines,
                    label=label,
                    platform=platform,
                    tags=tags,
                    archs=arch,
                    os_version=os_version
                )
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                machines = self.filter_machines_to_tasks(machines=machines,label=label,platform=platform,tags=tags,archs=arch,os_version=os_version,include_reserved=include_reserved)
```suggestion
                machines = self.filter_machines_to_tasks(
                    machines=machines,
                    label=label,
                    platform=platform,
                    tags=tags,
                    archs=arch,
                    os_version=os_version,
                    include_reserved=include_reserved
                )
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        #Add a check to ensure there is no more task thread created if the number of active analysis is greater than the total number of machines
```suggestion
        # Add a check to ensure there is no more task thread created if the number of active analysis is greater 
        # than the total number of machines
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +        #Resync of the lock value
```suggestion
        # Resync of the lock value
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                    #Prevent full starvation, very unlikely to ever happen.
```suggestion
                    # Prevent full starvation, very unlikely to ever happen.
```

2023-11-02 15:39 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                        # Max_batch_scheduling_count is refering to the batch_scheduling confing however this number is the maximum and capped for each usage by the number of locks available which re
```suggestion
                        # Max_batch_scheduling_count is referring to the batch_scheduling config however this number 
                        # is the maximum and capped for each usage by the number of locks available which refer to 
                        # the number of expected available machines.
```

2023-11-07 18:08 UTC, cccs-kevin approved these changes
Branch commits have been squashed/reworded; This is running in our production system. On Nov 14 we can move this to be a PR on the main upstream CAPEv2 repo.

2023-11-17 16:11 UTC, cccs-kevin requested changes

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> -
keep line

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +RUNNING = "running"
```suggestion
MACHINE_RUNNING = "running"
```

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> -
keep line

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    machines = machines.filter(or_(Machine.status.notlike(MACHINE_SCHEDULED),Machine.status == None))
```suggestion
                    machines = machines.filter(or_(Machine.status.notlike(MACHINE_SCHEDULED), Machine.status is None))
```

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                     # Get the first free machine.
```suggestion
                    # Get the first free machine.
```

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    #This loop is there in order to prevent double spending of machines by filtering out already mapped machines
```suggestion
                    # This loop is there in order to prevent double spending of machines by filtering 
                    # out already mapped machines
```

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                machines = self.filter_machines_to_task(machines=machines,label=label,platform=platform,tags=tags,archs=arch,os_version=os_version,include_reserved=include_reserved)
formatting

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> -
keep line

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +from lib.cuckoo.core.database import TASK_COMPLETED, TASK_FAILED_ANALYSIS, TASK_PENDING, Database, Task, RUNNING, MACHINE_SCHEDULED
```suggestion
from lib.cuckoo.core.database import TASK_COMPLETED, TASK_FAILED_ANALYSIS, TASK_PENDING, Database, Task, MACHINE_RUNNING, MACHINE_SCHEDULED
```

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +                machinery.set_status(self.machine.label, RUNNING)
```suggestion
                machinery.set_status(self.machine.label, MACHINE_RUNNING)
```

2023-11-17 16:11 UTC, cccs-kevin commented on lib/cuckoo/core/scheduler.py
> +tasks_in_limbo = []
remove all references to `tasks_in_limbo`

2023-11-17 17:48 UTC, cccs-kevin requested changes

2023-11-17 17:48 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    machines = machines.filter(or_(Machine.status.notlike(MACHINE_SCHEDULED),Machine.status is None))
```suggestion
                    machines = machines.filter(or_(Machine.status.notlike(MACHINE_SCHEDULED), Machine.status is None))
```

2023-11-21 13:00 UTC, cccs-kevin requested changes

2023-11-21 13:00 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
>          @param platform: optional virtual machine platform
add docstring for need_scheduled

2023-11-21 13:00 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    machines = machines.filter(Machine.status.like("scheduled"))
use enum rather than string

2023-11-22 13:49 UTC, cccs-kevin approved these changes

2023-12-11 16:06 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +                    machines = machines.filter(or_(Machine.status.notlike(MACHINE_SCHEDULED),Machine.status == None))
```suggestion
                    machines = machines.filter(or_(Machine.status.notlike(MACHINE_SCHEDULED), Machine.status is None))
```

2023-12-11 16:07 UTC, cccs-kevin commented on lib/cuckoo/core/database.py
> +    @classlock
This method is never used

2024-01-18 14:58 UTC, closed without merging