Cccs mog patch 1
cccs-mog/CAPEv2 pull request #5
Opened 2024-01-12 15:08 UTC by cccs-mog

2024-01-18 16:50 UTC, cccs-kevin requested changes
the big request is regarding the first signature vs the second signature

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +#filter_analysistypes = set(["file"])
```suggestion
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +    # This test can be used to validate if a specific report trigger your function the same way as process.py does. It could be used to test a suite of signature against known report.json files.
```suggestion
    # This test can be used to validate if a specific report trigger your function the same way as process.py does. 
    # It could be used to test a suite of signature against known report.json files.
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +    @pytest.mark.parametrize(
```suggestion

    @pytest.mark.parametrize(
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +class FakeSignatureNonFiltered(Signature):
If I am understanding this correctly, this signature is "evented" and contains filters, so it should have the same behaviour as `FakeSigFiltered` due to the intersection? The `if` statement in `FakeSigFiltered` is not necessary since those should be the only calls that it receives

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion


```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +class FakeSignatureAPI(Signature):
```suggestion

class FakeSignatureAPI(Signature):
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +class FakeSignatureProcess(Signature):
```suggestion

class FakeSignatureProcess(Signature):
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
        
        
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
```

2024-01-18 16:50 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion


```

2024-01-18 16:54 UTC, cccs-mog commented on tests/test_signature.py
> +class FakeSignatureNonFiltered(Signature):
Yes this is on purpose, this is to test if our filtering is working correctly, ie the behavior should be the same for both in the case that the filtering was not ( the on_call would be called when it's not supposed to and would trigger when it's not supposed to but not the double checked)

2024-01-18 17:00 UTC, cccs-kevin commented on tests/test_signature.py
> +class FakeSignatureNonFiltered(Signature):
oh, in that case, the `filter_*` should be removed from the FakeSignatureNonFiltered signature to avoid evented-related behaviours

2024-01-18 18:42 UTC, cccs-mog commented on tests/test_signature.py
> +class FakeSignatureNonFiltered(Signature):
You mean FakeSignatureFiltered ? They should both be evented and have filtering. The reason for the on_call if filtering is to validate that an OR doesn't occur. Obviously the ones that doesn't match are doing this as well but to another level. The reason for that is to prevent having more tests for every filtering problem there could be.

2024-01-18 19:41 UTC, cccs-kevin requested changes

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +    name = "FakeSig"
```suggestion
    name = "FakeSignatureNonFiltered"
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +                "FakeSig",
```suggestion
                "FakeSignatureNonFiltered",
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +                "FakeSig",
```suggestion
                "FakeSignatureNonFiltered",
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +        "task_id, signature_name, match_expected",
`match_expected` should instead be a list of signature names expected to match

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +        task = {}
```suggestion
        task = {"id": task_id}
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +                False,
this last test should have a list of all expected signature names that match, and there should be more than one in theory

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +            assert path_exists(report),"Missing test data file, failing"
```suggestion
            assert path_exists(report), "Missing test data file, failing"
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +            assert results is not None,"Test data file is empty"
```suggestion
            assert results is not None, "Test data file is empty"
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +            assert signature_name in results["statistics"]["signatures"][0]["name"],"Signature should be matching report"
```suggestion
            assert signature_name in results["statistics"]["signatures"][0]["name"], f"Signature should be matching report for task {task_id}"
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +            assert len(results["statistics"]["signatures"]) == 1,"{signature_name} should be the only signature ran"
```suggestion
            assert len(results["statistics"]["signatures"]) == 1, "{signature_name} should be the only signature run"
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +            assert signature_name not in results["signatures"],"Signature should not be matching report"
```suggestion
            assert signature_name not in results["signatures"], f"Signature should not be matching report for task {task_id}"
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +            assert len(results["signatures"]) == 0,"{signature_name} should have no signature matching"
```suggestion
            assert len(results["signatures"]) == 0, "{signature_name} should have no matching signature"
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +    def test_RunSignatures(self, task_id, signature_name, match_expected):
```suggestion
    def test_RunSignatures_run(self, task_id, signature_name, match_expected):
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +        if call["api"] == "gethostbyname":
```suggestion
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +        if process["process_name"] == "powershell.exe":
```suggestion
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +        if call["category"] == "network":
```suggestion
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +    authors = ["cccs-mog"]
```suggestion
    authors = ["@CybercentreCanada", "@cccs-mog"]
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +    authors = ["cccs-mog"]
```suggestion
    authors = ["@CybercentreCanada", "@cccs-mog"]
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +    authors = ["cccs-mog"]
```suggestion
    authors = ["@CybercentreCanada", "@cccs-mog"]
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +    authors = ["cccs-mog"]
```suggestion
    authors = ["@CybercentreCanada", "@cccs-mog"]
```

2024-01-18 19:41 UTC, cccs-kevin commented on tests/test_signature.py
> +    authors = ["cccs-mog"]
```suggestion
    authors = ["@CybercentreCanada", "@cccs-mog"]
```

2024-01-19 19:06 UTC, cccs-kevin requested changes

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion


```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
        
        
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
        
        
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion


```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +
```suggestion


```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +class FakeSignatureNonFiltered(Signature):
This signature is quite filtered, so can we rename it to `FakeSignatureAPI_Cat_Process_With_No_OnCall_Check`?

```suggestion
class FakeSignatureAPI_Cat_Process_With_No_OnCall_Check(Signature):
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +class FakeSignatureFiltered(Signature):
Small naming change for clarity

```suggestion
class FakeSignatureAPI_Cat_Process_With_OnCall_Check(Signature):
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +            # Single signature with two filter which should match
Can we add a test for `FakeSignatureCallAlways` where it doesn't match please?

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +            ),
Can also add this test for test data 1 and 3 please?

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +            ),
FakeAPI, FakeSigFiltered, FakeSignatureAPI_Process and FakeSignatureAPI_Cat should not hit on test data 2 because test data 2 does not have "gethostbyname"

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +        print(results)
```suggestion
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +        if match_expected and isinstance(match_expected,bool):
```suggestion
        if match_expected and isinstance(match_expected, bool):
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +            assert len(results["statistics"]["signatures"]) == 1, "{signature_name} should be the only signature run"
```suggestion
            assert len(results["statistics"]["signatures"]) == 1, f"{signature_name} should be the only signature run"
```

2024-01-19 19:06 UTC, cccs-kevin commented on tests/test_signature.py
> +                assert match in triggered,"Signature should be matching report"
```suggestion
                assert match in triggered, "Signature should be matching report"
```

2024-01-22 16:32 UTC, merged